### ISSUE TITLE
Vim hangs on typing "in" at the beginning of a line

### ISSUE THREAD

**Issue by gkotian** [JesseKPhillips/d.vim#22]
I noticed the weirdest thing yesterday, when I wanted to change a `void main()` to `int main()`. Vim just froze, and refused to do anything until I did a `Ctrl+c`.

On digging further, I saw that this happened only with `.d` files, so I thought the `d.vim` plugin may have something to do with it. If I disable `d.vim` using:
```
set runtimepath-=~/.vim/bundle/d.vim
set runtimepath-=~/.vim/bundle/d.vim/after
```
in my vimrc, then Vim doesn't hang. This seems to confirm that the issue may lie in something that's going on in `d.vim`.

To reproduce it, all you need to do is open any `.d` file (with d.vim enabled of course), and type `i` followed by `n`. That's it. The CPU usage of Vim should spike to 100%, and it should just freeze. `Ctrl+c` does get you out of it though.

Note that this happens only when typing `i` followed by `n` at the start of a line. I can happily type `in` anywhere else without issues!

Using latest d.vim, with Vim version 7.3 running on Ubuntu 13.10 64 bit.

**Comment by rcorre** [comment]
The solution linked by @tamy0612 works for me, any chance of getting a PR in?

**Comment by whitebyte** [comment]
...anybody home? @JesseKPhillips could we please have this fix merged? It seems to be trivial yet useful.

**Comment by JesseKPhillips** [comment]
@whitebyte, apologies please feel free to merge it in if I don't get to it first.
