### ISSUE TITLE
2D array literal indentation

### ISSUE THREAD

**Issue by rcorre** [JesseKPhillips/d.vim#26]
The following declaration:

```
auto a = [
    [ 1, 2, 3, 4 ],
    [ 1, 2, 3, 4 ],
    [ 1, 2, 3, 4 ],
    [ 1, 2, 3, 4 ],
];
```

is indented like so (when using `==`):
```
auto a = [
    [ 1, 2, 3, 4 ],
    [ 1, 2, 3, 4 ],
        [ 1, 2, 3, 4 ],
            [ 1, 2, 3, 4 ],
];
```

**Comment by JesseKPhillips** [comment]
I've been unable to reproduce this, both with and without the indent file installed.

**Comment by rcorre** [comment]
looks like it only happens inside a block:

```
unittest {
auto a = [
    [ 1, 2, 3, 4 ],
    [ 1, 2, 3, 4 ],
    [ 1, 2, 3, 4 ],
    [ 1, 2, 3, 4 ],
];
}
```

With the cursor at the top, press `=G`
```

**Comment by JesseKPhillips** [comment]
Still not observing this behavior, will need to verify that I am getting the indent file to load.

**Comment by whitebyte** [comment]
I can reproduce this bug, and suggested solution seems to resolve it. @rcorre mind creating a PR?
