### ISSUE TITLE
neovim's runtime files for D are outdated

### ISSUE THREAD

**Issue by ZombineDev** [JesseKPhillips/d.vim#31]
Looking at neovim, I found that its D files are quite [outdated](https://github.com/neovim/neovim/blob/master/runtime/syntax/d.vim). I'm not familiar with neither vim, nor neovim's development processes, so I'm not sure whom to reach to request an update.
Can you help me get neovim's D support updated?

**Comment by JesseKPhillips** [comment]
It is not very outdated, I believe it is only one version behind what has been submitted to the upstream vim repository. I would expect the NeoVim team is tracking upstream, but not synchronizing very often. If you want to reach out to NeoVim and let me know what their update process consists of I can include it when doing a release.
